# Generated by Django 4.1 on 2022-10-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_comment_tags_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('AS', 'African_Story'), ('MYS2', 'MyStory_YourStory'), ('OD', 'Our_Discoveries'), ('TS', 'Tech_Stories'), ('L', 'Lifestyle')], default='OD', max_length=5),
        ),
    ]
